### ISSUE TITLE
Ansible 之 Playbooks

### ISSUE THREAD

**Issue by felix-cao** [felix-cao/Blog#172]
## 一、理解 Playbook 概念
`PlayBook` 是 `Ansible` 自动化中非常重要的概念， 在[《Ansible 安装与配置》](https://github.com/felix-cao/Blog/issues/172)  中，文章的最后，我们用 `ansible all -m ping -u admin` 命令行做了一次测试。

`PlayBook` 是由一个或多个 `play` 组成的列表，`play` 的主要功能是为 `Ansible` 中的 `task` 定义好的角色，指定剧本对应的服务器组。 `task`是一个任务，`task` 可以调用 `Ansible` 的各种模块，将多个`play`组织在一个`playbook`剧本中，全部组成一个完整的流程控制集合

我个人把他理解为 `Ansible` 自动化流程中的配置文件，像是 `Node.js` 中的 `package.json`， 也像是 `Docker` 中的 `Dockerfile`。

## 二、PlayBook 四个组成部分
- `target：`  定义 `PlayBook` 的远程主机组
- `variable：` 定义PlayBook使用的变量
- `task：` 定义远程主机上执行的任务列表
- `handler：` 定义task执行完成后需要调用的任务，例如修改配置文件之后，启动跟handler任务重启相关联的服务

### 2.1、target 常用参数详解
- `hosts：` 定义远程主机组
- `user：` 执行该任务的用户
- `sudo：` 设置为yes的时候，执行任务使用root权限
- `sudo_user：` 指定sudo的普通用户
- `connection：` 默认基于SSH链接客户端
- `gather_facks：` 获取远程主机facts基础信息

### 2.2、variable 常用参数详解

- `vars：` 定义格式，变量名：变量值
- `vars_files：` 指定变量文件
- `vars_prompt：` 用户交互模式自定义变量
- `setup：` 模块取远程主机的值

### 2.3、task 常用参数详解
- `name：` 任务显示名称也是屏幕显示信息
- `action：` 定义执行的动作
- `copy：` 复制本地文件到远程主机
- `template：` 复制本地文件到远程主机，可以引用本地变量
- `service：` 定义服务的状态

## 三、简单的 playbook 案例

下面我们通过一个简单的小 `Demo` 来入门一下 `playbook`

```
- hosts: weixin_H5
   user: admin
   sudo: yes
   vars:
     port: 9080
     http: www.qu-ma.cn

   tasks:
     - name: Create The folder
       file:
         path: /home/test/
         state: directory
         owner: admin
         group: www

     - name: Push The Code To The folder
       template:
         src: /home/antest/test.txt
         dest: /home/test/text.txt
``` 

**解读**
- weixin_H5， 是一组主机清单的分组名称，请阅读[《Ansible 安装与配置》](https://github.com/felix-cao/Blog/issues/172)  中的主机清单配置
- `user: admin`，`user` 是 `target` 部分配置的，表示在 `weixin_H5` 执行该任务的用户是 `admin`
- `sudo: yes`，以 root 方式去执行
- `vars` 定义了 `port` 和 `http` 两个变量， 这两个变量可以直接在下面使用，如在 `/home/antest/test.txt` 这个文件中使用了这两个变量
- `tasks` 部分定义了两个，第一个是创建文件夹，第二个是复制文件
- 创建文件夹是用了 `ansible` 的 `file` 模块
- 复制文件是用了`ansible` 的 `template` 模块

最后执行一把：

```
$ ansible-playbook ./test.yml
```

<img src="https://user-images.githubusercontent.com/8563874/57015226-296c8880-6c46-11e9-8edf-cf25062f7040.png" width=500/>

上图可以看到，两个 `task` 执行是成功的。如果我们把 `state` 设置为 `absent` 呢？

```
        path: /home/test/
        state: absent
        # state: directory
        # owner: admin
        # group: www
```

表示删除 `/home/test/` 这个目录了。

**Comment by felix-cao** [comment]
## 在指定目录中执行命令

在 `/home/wwwroot/apis` 目录下执行 `composer install`

```
- name: Install Dependence with composer
      command: /usr/local/bin/composer install
      args:
        chdir: /home/wwwroot/apis
```

**Comment by felix-cao** [comment]
# pipeline
## 一、在 git 服务器上执行 ansible-playbook
### 1.1、添加 ip 到 host
```
vi /etc/ansible/hosts
```
### 2.2、

**Comment by felix-cao** [comment]
# 文件中含有特殊符号的 ansible 替换
比如 php 文件中含有

```php
private $host='127.0.0.1';   //主机地址
private $port='3306';     //端口号
private $user='quma';     //用户名
private $pass='quma2019';     //密码
```

```
- name: Modify the DB config file for dinner
      lineinfile:
        dest: '{{config_dinner_db}}'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '\$host', line: '    private $host="127.0.0.1";'}
        - { regexp: '\$user', line: '    private $user="quma___";'}
        - { regexp: '\$pass', line: '    private $pass="123456666";'}
```
